# Generated by Django 3.2.4 on 2021-06-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Слова')),
                ('example', models.CharField(max_length=255, verbose_name='Пример в тексте')),
                ('transcript', models.CharField(max_length=255, verbose_name='Транскрипция')),
                ('translation', models.CharField(max_length=255, verbose_name='Перевод слова')),
                ('example_translate', models.CharField(max_length=255, verbose_name='Пример перевода в тексте')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение')),
                ('links_image', models.CharField(max_length=255, verbose_name='Ссылка на ресурс картинки')),
                ('is_free', models.BooleanField(default=False, verbose_name='Статус бесплатно')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='translator.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='translator.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['category'],
            },
        ),
    ]
